"""
Main entry point for the scaldys-builder build system.

This script provides a unified CLI for building projects across different
platforms.  Currently supports Windows builds (documentation, executables,
and installers).

Run from the root of the consuming project::

    scaldys-build build windows all
"""

import logging
from pathlib import Path
import typer
from rich.console import Console
from rich.logging import RichHandler

from scaldys_builder.windows.builder import WindowsBuilder


def _find_project_root() -> Path:
    """
    Walk up from the current directory to find the project root.

    The project root is identified as the first directory containing a
    ``pyproject.toml`` file.  Falls back to ``cwd`` if none is found.
    """
    cwd = Path.cwd()
    for candidate in [cwd, *cwd.parents]:
        if (candidate / "pyproject.toml").exists():
            return candidate
    return cwd


PROJECT_ROOT = _find_project_root()

# Configure logging
console = Console()
logging.basicConfig(
    level=logging.INFO,
    format="%(message)s",
    datefmt="[%X]",
    handlers=[RichHandler(rich_tracebacks=True, console=console, show_path=False, markup=True)],
)
logger = logging.getLogger(__name__)

app = typer.Typer(help="Scaldys Builder", no_args_is_help=True)
build_app = typer.Typer(help="Build subcommands", no_args_is_help=True)
windows_app = typer.Typer(help="Windows specific build subcommands", no_args_is_help=True)

app.add_typer(build_app, name="build")
build_app.add_typer(windows_app, name="windows")


@windows_app.command("docs")
def windows_docs(
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output."),
) -> None:
    """Build Windows documentation."""
    builder = WindowsBuilder(PROJECT_ROOT, verbose=verbose)
    builder.env.pre_flight_checks(require_sphinx=True)
    builder.build_docs()


@windows_app.command("exe")
def windows_exe(
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output."),
) -> None:
    """Build Windows executables."""
    builder = WindowsBuilder(PROJECT_ROOT, verbose=verbose)
    builder.build_exe()


@windows_app.command("installer")
def windows_installer(
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output."),
) -> None:
    """Build Windows setup installer."""
    builder = WindowsBuilder(PROJECT_ROOT, verbose=verbose)
    builder.build_installer()


@windows_app.command("all")
def windows_all(
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output."),
) -> None:
    """Run the complete end-to-end Windows build workflow."""
    builder = WindowsBuilder(PROJECT_ROOT, verbose=verbose)
    builder.main(console=console)


@windows_app.command("clean")
def windows_clean(
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output."),
) -> None:
    """Clean out files generated by previous build."""
    builder = WindowsBuilder(PROJECT_ROOT, verbose=verbose)
    builder.clean()


if __name__ == "__main__":
    app()
